# Generated by Django 2.0.5 on 2018-05-13 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('n_tx', models.IntegerField()),
                ('total_received', models.BigIntegerField()),
                ('total_sent', models.BigIntegerField()),
                ('final_balance', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_id', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('output', models.BigIntegerField()),
                ('time', models.DateTimeField()),
                ('addressRel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockform.Address')),
            ],
        ),
    ]
