# Generated by Django 2.0.5 on 2018-05-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockform', '0003_remove_transaction_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='output',
            field=models.BigIntegerField(default=0),
        ),
    ]
