# Generated by Django 2.0.5 on 2018-05-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockform', '0009_auto_20180513_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='negativeoutput',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
