# Generated by Django 2.0.5 on 2018-05-14 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockform', '0010_transaction_negativeoutput'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
